# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-03-22 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirRNAInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancer_info_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100, null=True, verbose_name='disease')),
                ('DOID', models.CharField(max_length=500, null=True, verbose_name='DOID')),
                ('Definition', models.CharField(max_length=500, null=True, verbose_name='DOID')),
                ('Xrefs', models.CharField(max_length=500, null=True, verbose_name='Xrefs')),
                ('Subsets', models.CharField(max_length=500, null=True, verbose_name='Subsets')),
                ('Synonyms', models.CharField(max_length=500, null=True, verbose_name='Synoyms')),
                ('Relationships', models.CharField(max_length=500, null=True, verbose_name='Relationships')),
            ],
        ),
        migrations.CreateModel(
            name='circRNA_cancer_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circRNA', models.CharField(max_length=100, null=True, verbose_name='circRNA')),
                ('disease', models.CharField(max_length=100, null=True, verbose_name='disease')),
                ('method_of_circRNA_direction', models.CharField(max_length=100, null=True, verbose_name='method_of_circRNA_direction')),
                ('expression_pattern', models.CharField(max_length=100, null=True, verbose_name='expression_pattern')),
                ('Chromosome', models.CharField(max_length=100, null=True, verbose_name='Chromosome')),
                ('Region', models.CharField(max_length=100, null=True, verbose_name='Region')),
                ('Strand', models.CharField(max_length=100, null=True, verbose_name='strand')),
                ('Gene_Symbol', models.CharField(max_length=100, null=True, verbose_name='Gene_Symbol')),
                ('host_gene', models.CharField(max_length=100, null=True, verbose_name='host_gene')),
                ('tissue_or_cell_line', models.CharField(max_length=100, null=True, verbose_name='tissue_or_cell_line')),
                ('Transcription_interval', models.CharField(max_length=100, null=True, verbose_name='Transcription_interval')),
                ('species', models.CharField(max_length=100, null=True, verbose_name='species')),
                ('pmid', models.CharField(max_length=100, null=True, verbose_name='pmid')),
                ('functional_describution', models.CharField(max_length=500, null=True, verbose_name='functional_describution')),
                ('sequence', models.CharField(max_length=500, null=True, verbose_name='sequence')),
            ],
        ),
        migrations.CreateModel(
            name='circrna_info_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circRNA', models.CharField(max_length=500, null=True, verbose_name='circRNA')),
                ('method_of_circRNA_direction', models.CharField(max_length=500, null=True, verbose_name='method_of_circRNA_direction')),
                ('expression_pattern', models.CharField(max_length=100, null=True, verbose_name='expression_pattern')),
                ('Chromosome', models.CharField(max_length=100, null=True, verbose_name='Chromosome')),
                ('Region', models.CharField(max_length=100, null=True, verbose_name='Region')),
                ('Strand', models.CharField(max_length=100, null=True, verbose_name='Strand')),
                ('Gene_Symbol', models.CharField(max_length=100, null=True, verbose_name='Gene_Sym')),
                ('host_gene', models.CharField(max_length=100, null=True, verbose_name='host_gene')),
                ('tissue_or_cell_line', models.CharField(max_length=100, null=True, verbose_name='tissue_cell')),
                ('Transcription_interval', models.CharField(max_length=200, null=True, verbose_name='Transcription_interval')),
                ('Sequence', models.CharField(max_length=500, null=True, verbose_name='Sequence')),
            ],
        ),
        migrations.DeleteModel(
            name='cirrna',
        ),
        migrations.DeleteModel(
            name='disease',
        ),
        migrations.DeleteModel(
            name='relationship',
        ),
    ]
