from django.db import models
class circRNA_miRNA(models.Model):
    circRNA = models.CharField("circRNA",max_length=100,null=True)
    miRNA = models.CharField("miRNA",max_length=100,null=True)
class cancer_info(models.Model):
    disease=models.CharField("disease",max_length=100,null=True)
    DOID=models.CharField("DOID",max_length=500,null=True)
    Definition=models.CharField("DOID",max_length=500,null=True)
    Xrefs=models.CharField("Xrefs",max_length=500,null=True)
    Subsets=models.CharField("Subsets",max_length=500,null=True)
    Synonyms=models.CharField("Synoyms",max_length=500,null=True)
    Relationships=models.CharField("Relationships",max_length=500,null=True)
class circRNA_cancer(models.Model):
    circRNA=models.CharField("circRNA",max_length=100,null=True)
    disease=models.CharField("disease",max_length=100,null=True)
    method_of_circRNA_direction=models.CharField("method_of_circRNA_direction",max_length=100,null=True)
    expression_pattern=models.CharField("expression_pattern",max_length=100,null=True)
    Chromosome=models.CharField("Chromosome",max_length=100,null=True)
    Region=models.CharField("Region",max_length=100,null=True)
    Strand=models.CharField("strand",max_length=100,null=True)
    Gene_Symbol=models.CharField("Gene_Symbol",max_length=100,null=True)
    host_gene=models.CharField("host_gene",max_length=100,null=True)
    tissue_or_cell_line=models.CharField("tissue_or_cell_line",max_length=100,null=True)
    Transcription_interval=models.CharField("Transcription_interval",max_length=100,null=True)
    species=models.CharField("species",max_length=100,null=True)
    pmid=models.CharField("pmid",max_length=100,null=True)
    functional_describution=models.CharField("functional_describution",max_length=500,null=True)
    sequence=models.CharField("sequence",max_length=500,null=True)
class miRNA_cancer(models.Model):
    miRNA=models.CharField("circRNA",max_length=100,null=True)
    disease = models.CharField("disease", max_length=100, null=True)
    pmid=models.CharField("pmid",max_length=100,null=True)
    description=models.CharField("description",max_length=500,null=True)
class miRNA_info(models.Model):
    miRNA=models.CharField("circRNA",max_length=100,null=True)
    Accession=models.CharField("Accession",max_length=100,null=True)
    symbol=models.CharField("symbol",max_length=100,null=True)
    description=models.CharField("description",max_length=500,null=True)
    gene_family=models.CharField("gene_family",max_length=100,null=True)
    Genome_context=models.CharField("Genome_context",max_length=500,null=True)
    Clustered_miRNAs=models.CharField("Clustered_miRNAs",max_length=500,null=True)
    database_links=models.CharField("database_links",max_length=500,null=True)
class circrna_info(models.Model):
    circRNA = models.CharField("circRNA",max_length=500,null=True)
    method_of_circRNA_direction = models.CharField("method_of_circRNA_direction",max_length=500,null=True)
    expression_pattern = models.CharField("expression_pattern",max_length=100,null=True)
    Chromosome = models.CharField("Chromosome",max_length=100,null=True)
    Region = models.CharField("Region",max_length = 100,null = True )
    Strand = models.CharField("Strand",max_length = 100,null = True )
    Gene_Symbol = models.CharField("Gene_Sym",max_length= 100,null=True)
    host_gene = models.CharField("host_gene",max_length=100,null=True)
    tissue_or_cell_line = models.CharField("tissue_cell",max_length=100,null=True)
    Transcription_interval = models.CharField("Transcription_interval",max_length=200,null=True)
    Sequence = models.CharField("Sequence", max_length=500,null=True)
class circrna_info_test(models.Model):
    circRNA = models.CharField("circRNA",max_length=500,null=True)
    method_of_circRNA_direction = models.CharField("method_of_circRNA_direction",max_length=500,null=True)
    expression_pattern = models.CharField("expression_pattern",max_length=100,null=True)
    Chromosome = models.CharField("Chromosome",max_length=100,null=True)
    Region = models.CharField("Region",max_length = 100,null = True )
    Strand = models.CharField("Strand",max_length = 100,null = True )
    Gene_Symbol = models.CharField("Gene_Sym",max_length= 100,null=True)
    host_gene = models.CharField("host_gene",max_length=100,null=True)
    tissue_or_cell_line = models.CharField("tissue_cell",max_length=100,null=True)
    Transcription_interval = models.CharField("Transcription_interval",max_length=200,null=True)
    Sequence = models.CharField("Sequence", max_length=500,null=True)
class circRNA_cancer_test(models.Model):
    circRNA=models.CharField("circRNA",max_length=100,null=True)
    disease=models.CharField("disease",max_length=100,null=True)
    method_of_circRNA_direction=models.CharField("method_of_circRNA_direction",max_length=100,null=True)
    expression_pattern=models.CharField("expression_pattern",max_length=100,null=True)
    Chromosome=models.CharField("Chromosome",max_length=100,null=True)
    Region=models.CharField("Region",max_length=100,null=True)
    Strand=models.CharField("strand",max_length=100,null=True)
    Gene_Symbol=models.CharField("Gene_Symbol",max_length=100,null=True)
    host_gene=models.CharField("host_gene",max_length=100,null=True)
    tissue_or_cell_line=models.CharField("tissue_or_cell_line",max_length=100,null=True)
    Transcription_interval=models.CharField("Transcription_interval",max_length=100,null=True)
    species=models.CharField("species",max_length=100,null=True)
    pmid=models.CharField("pmid",max_length=100,null=True)
    functional_describution=models.CharField("functional_describution",max_length=500,null=True)
    sequence=models.CharField("sequence",max_length=500,null=True)
class cancer_info_test(models.Model):
    disease = models.CharField("disease", max_length=100, null=True)
    DOID = models.CharField("DOID", max_length=500, null=True)
    Definition = models.CharField("DOID", max_length=500, null=True)
    Xrefs = models.CharField("Xrefs", max_length=500, null=True)
    Subsets = models.CharField("Subsets", max_length=500, null=True)
    Synonyms = models.CharField("Synoyms", max_length=500, null=True)
    Relationships = models.CharField("Relationships", max_length=500, null=True)